RegisterServerEvent('xC_Libraries:ClientErrorLog')
AddEventHandler('xC_Libraries:ClientErrorLog', function(res, ...)
    print("-----------------------------------------------------")
    print("ID: "..source.." | Script: "..res.." | Error: ")
    print(...)
    print("-----------------------------------------------------")
end)
